### ISSUE TITLE
Could not find helper

### ISSUE THREAD

**Issue by SparrowJang** [SlexAxton/require-handlebars-plugin#138]
I get this error.

```
Uncaught Error: Could not find property 'equal'
```

**Render data**:

```
products = [{id:1},{id:2}];
```

**Template**:

```
{{#each products}}
  {{# equal @index 1 }}

    <!--  doSomething -->
  {{/equal}}

{{/each}}
```

The helper isn't loaded.

```
{{#each products}}
  {{# equal @index 1  id}}

    <!--  doSomething -->
  {{/equal}}

{{/each}}
```

Get a helper if you use input parameter.

**Require config**(coffee script):

```
require.config
  disableHelpers: false
  templateExtension: 'hbs'
  helperPathCallback:( name )-> "/scripts/templates/helpers/#{name}.js"
  compileOptions: {}
```

**Comment by pcompassion** [comment]
So I need to use hbs/handlebars in helper module.

Do I need to use `hbs/handlebars` in other parts of my code as well?

**Comment by nleclerc** [comment]
@pcompassion of course.
BTW you should really drop this plugin and use precompiled templates anyway.

**Comment by pcompassion** [comment]
@nleclerc Thank you!

Why do you say so?

I did apply this plugin and found no speed up ..
I guess you have the answer to it.

**Comment by nleclerc** [comment]
well, i'm using grunt for build and to run a dev server so i just add template compilation during live reload and actual build.
I've found that this plugin has too much baggage and doesn't move forward fast enough anyway.

The grunt module is [grunt-contrib-handlebars](https://github.com/gruntjs/grunt-contrib-handlebars).

**Comment by poc7667** [comment]
@craigjennings11  you saved me, thank you

**Comment by nleclerc** [comment]
N/p :-)
