### ISSUE TITLE
Dynamic partials

### ISSUE THREAD

**Issue by MadebyAe** [SlexAxton/require-handlebars-plugin#224]
I want render a partial with the handlebar partial method "{{> partial/name}}" 

``{{#each cars}}``
 ``<!-- load partial dynamically this.slug = bmw -->``
 ``{{> this.slug}}``

``{{/each}}``

It's possible?

**Comment by chrisrink** [comment]
Dynamic partials come in handlebars 3. See pull request  #236

**Comment by MadebyAe** [comment]
Thanks :)
