### ISSUE TITLE
lots of 'unnormalized' template files failing to load

### ISSUE THREAD

**Issue by bigfish** [SlexAxton/require-handlebars-plugin#70]
Using the 4.0 version with RequireJS 2.1.1 I'm getting this error:

Error: Load timeout for modules: hbs!template/LoginForm_unnormalized2,hbs!template/SetInitialPassword_unnormalized3,hbs!template/SetInitialPassword_Expired_unnormalized4,hbs!template/Header_unnormalized5,hbs!template/Footer_unnormalized6,hbs!template/accounts/Accounts_unnormalized7,hbs!template/accounts/AccountTenantPerms_unnormalized8,hbs!template/accounts/AddAccountForm_unnormalized9,...

This is the related parts of requirejs config 

    paths: {
     ...
        hbs: "../assets/js/libs/hbs",
        Handlebars: "../assets/js/libs/Handlebars",

        //requirejs handlebars plugin dependencies:
        handlebars : "../assets/js/libs/Handlebars",
        underscore : "../assets/js/libs/hbs/underscore",
        i18nprecompile : "../assets/js/libs/hbs/i18nprecompile",
        json2 : "../assets/js/libs/hbs/json2",

     ...
    },

//this stuff from demo project:

    optimizeCss: "standard",
    inlineText: true,
    // hbs config
    pragmasOnSave: {
        //removes Handlebars.Parser code (used to compile template strings) set
        //it to `false` if you need to parse template strings even after build
        excludeHbsParser : true,
        // kills the entire plugin set once it's built.
        excludeHbs: true,
        // removes i18n precompiler, handlebars and json2
        excludeAfterBuild: true
    },
    hbs: {
        disableI18n: false,
        // This disables the i18n helper and
        // doesn't require the json i18n files (e.g. en_us.json)
        // (false by default)
        disableHelpers: false,
        // When true, won't look for and try to automatically load
        // helpers (false by default)
        // Callback to determine the path to look for helpers:
        helperPathCallback: function (name) { // ('/template/helpers/'+name by default)
            return 'cs!' + name;
        },
        partialPath: '/template/',
        templateExtension: "hbs" // Set the extension automatically appended to templates
    },

**Comment by mattkime** [comment]
move to close. this appears resolved.
